---
title: "DescriptiveAnalysis"
author: "Simon Hettrick"
date: "12 May 2015"
output: html_document
---

Script
-------
```{r}
#Need the strignr package for the str_trim function that allows whitespace to be trimmed from a string
library(stringr)
library(knitr)

```

Read cleaned data into data frame

```{r}
#Don't want strings as factors because it makes later changes difficult, and want any blank response inserted as "NA"
data_cleaned<-read.csv("../data/mergedDfCleaned.csv", stringsAsFactors=TRUE, na.strings="")

```

This loop goes to all the questions stated at the beggining of the function. It gives descriptive information about the frequencies of all the factors.

```{r kable xtable star, results='asis', fig.width = 20 ,fig.height = 10}
#install.packages('xtable')
#install.packages('RGraphics')
#install.packages('gridExtra')
#library(stargazer, quietly = TRUE)
library(xtable)
library(knitr)
library(grid)
library(gridExtra) 
#library(RGraphics)
library(ggplot2) 
library(scales)
```

```{r}
#extract legend
#https://github.com/hadley/ggplot2/wiki/Share-a-legend-between-two-ggplot2-graphs
g_legend<-function(a.gplot){
    tmp <- ggplot_gtable(ggplot_build(a.gplot))
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    legend <- tmp$grobs[[leg]]
    return(legend)}
```

```{r}
for (i in c('Q.1.Institution', 'Q.3.Discipline', 'Q.4.Funds.clean', 'Q.5.Seniority', 'Q.6.Use.Software', 'Q.7.Importance.Software',
            'Q.8.Developing.Software', 'Q.10.Cost.Software', 'E.1.Job.clean', 'E.2.Gender', 'E.3.Contract', 'E.4.OS.clean'))
    {
    table_factor = table(data_cleaned[,i])
    # Cbind is to combine two different sets into one data.frame
    # the conversion of data.frame within the cbind is to avoid having
    # the factor in data_row for the frequency
    # And being able to index only the value for the percentage
    QSummary<- cbind(as.data.frame(table_factor), 
                  as.data.frame(round(prop.table(table_factor)*100))[,2])
    
    #rename the column names
    colnames(QSummary) <- c(i, 'Total Respondant', 'Percent')
    # Order the table by Total Respondents 
    QSummary <- QSummary[order(QSummary[,2]),]
    # Output a table of the variable
    tableK <- kable(QSummary, digits=2)
    # Create a Pie chart with the percentage
    g1 <- ggplot(QSummary, aes(x=factor(1), y=QSummary$Percent, fill=QSummary[,i] ))
    g1 <- g1 + geom_bar(stat='identity')
    g1 <- g1 + geom_bar(width=1)
    g1 <- g1 + coord_polar(theta='y')
    g1 <- g1 + scale_y_continuous(breaks=cumsum(QSummary$Percent), labels=QSummary$Percent)
    
    g1 <- g1 +theme_minimal()
    #g1 <- g1 + scale_fill_brewer(palette='Set1')
    g1 <- g1 + theme(axis.ticks=element_blank())
    g1 <- g1 + theme(legend.title=element_blank())
    g1 <- g1 + theme(axis.text.x= element_blank()) 
    g1 <- g1 + theme(axis.title.x= element_blank())
    #g1 <- g1 + theme(axis.title.y=element_blank())
    g1 <- g1 + theme(axis.text.y= element_blank()) 
    g1 <- g1 + xlab('Percent')
    g1 <- g1 + guides(s=guide_legend(ncol=2))
    # Plotting a histogram with the total respondents for each questions.
    g2 <- ggplot(QSummary, aes(x=QSummary[,i], y=QSummary$`Total Respondant`, fill=QSummary[,i]))
    g2 <- g2 + geom_bar(stat='identity')
    g2 <- g2 + theme(legend.title=element_blank())
    g2 <- g2 + theme(axis.text.x= element_blank()) 
    g2 <- g2 + theme(axis.title.x=element_blank())
    g2 <- g2 + ylab('Total Respondents')
    g2 <- g2 + geom_text(aes(label=QSummary$`Total Respondant`), vjust=0, size=4)
    g2 <- g2 + theme(legend.position='none')

    legend <- g_legend(g1)
    #Put the two graphs side-by-side
    g3 <- grid.arrange(arrangeGrob(g1+theme(legend.position='none'),g2, nrow=2), legend, ncol=2)
    
    #Assign create a variable containing the Summary
    assign(i, QSummary)
    # Remove the generated variables to keep the environment clean
    rm(QSummary,legend,g1,g2,g3,table_factor,i)
}
```